### ISSUE TITLE
Where is the file videojs-nle-controls.min.js?

### ISSUE THREAD

**Issue by matiaszumbo** [rochester-rcl/rcl-vjs-nle#1]

**Comment by jjromphf** [comment]
Hi @matiaszumbo, this is a really old project and hasn't been updated in a long time. After running npm install the dist folder will appear, but it looks like there's a few errors that are preventing this from happening. Let me update it for you within the next couple of days.

**Comment by matiaszumbo** [comment]
Ok thanks!

**Comment by jjromphf** [comment]
Hi @matiaszumbo I've updated the plugin to the most recent Video.js yeoman generator and all is working again. You can pull from the master branch and follow the instructions in the README - hopefully it works for you.

**Comment by matiaszumbo** [comment]
Excellent! Thanks

Its working now.

I try to add some adicional features
Like get timecode to do marks tcin tcout
And init the video with a start timecode

Later a can share de new version of code.

**Comment by jjromphf** [comment]
@matiaszumbo Awesome, thanks! I'll go ahead and close this now.
